# Generated by Django 4.0.4 on 2022-06-03 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(max_length=256)),
                ('validatetime', models.DateTimeField()),
                ('dob', models.DateField()),
                ('profile_pic', models.ImageField(blank=True, default='../media/profile/img6Q.png', upload_to='profile')),
            ],
        ),
    ]
