# Generated by Django 4.0.4 on 2022-05-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_id_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='../media/profile/img6Q.png', upload_to='profile'),
        ),
    ]
