# Generated by Django 4.0.4 on 2022-05-26 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default='../static/image404.png', upload_to='blogimage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='imgthumb',
            field=models.ImageField(blank=True, default='../static/image404.png', upload_to='blogthumb'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blogger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
