# Generated by Django 4.0.4 on 2022-05-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_id_alter_blog_blogger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='imgthumb',
        ),
    ]
