# Generated by Django 4.0.4 on 2022-05-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_imgthumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default='..\\media\\blogimage\\Screenshot_2022-01-15_162834.jpg', upload_to='blogimage'),
        ),
    ]
