# Generated by Django 4.0.4 on 2022-05-29 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 29, 11, 54, 38, 319874)),
            preserve_default=False,
        ),
    ]
